#!/bin/bash


PROJECT_ROOT=$(cd "$(dirname "$0")/../.." && pwd)


cd "$PROJECT_ROOT/terraform-full" || { printf "Error: Unable to navigate to the Terraform directory.\n" >&2; exit 1; }
terraform plan && terraform destroy -auto-approve

