apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - name: redis
      port: 6379
      nodePort: 32000
      targetPort: 6379
  selector:
    app.kubernetes.io/component: master
    app.kubernetes.io/instance: my-redis
    app.kubernetes.io/name: redis
