apiVersion: v1
kind: Service
metadata:
  name: postgresql-nodeport
  labels:
    app: postgresql
spec:
  type: NodePort
  ports:
    - name: postgresql
      port: 5432
      nodePort: 31000
      targetPort: 5432
  selector:
    app.kubernetes.io/name: postgresql
